# -*- coding: utf-8 -*-
"""Electra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4-NK6nJRuEpkfuY_LJOhgAVIwnxX5Jl
"""

!apt-get install tesseract-ocr -y
!pip install pytesseract

!pip install python-docx transformers

from google.colab import files
uploaded = files.upload()

#Extract the filename
file_name = list(uploaded.keys())[0]

import docx

# Function to extract text from a Word document
def read_word_file(file_path):
    doc = docx.Document(file_path)
    full_text = []
    for para in doc.paragraphs:
        full_text.append(para.text)
    return '\n'.join(full_text)

# Specify the file path (this will be the uploaded file's name)
file_path = 'Received April 1.docx'  # Replace with your actual filename
doc_content = read_word_file(file_path)

# Print the content (optional)
#print(doc_content)

"""**ELECTRA**"""

from transformers import ElectraTokenizer, ElectraForQuestionAnswering, pipeline

tokenizer = ElectraTokenizer.from_pretrained('google/electra-large-discriminator')
model = ElectraForQuestionAnswering.from_pretrained('google/electra-large-discriminator')
# Define the question and the document content
question = "What is the main point of this paper?"
context = doc_content  # Ensure this is properly extracted from your document
nlp = pipeline("question-answering", model=model, tokenizer=tokenizer)
result = nlp(question=question, context=context )
print(f"Answer: {result['answer']}")